baseURL = "https://maltby.dev"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
theme = "hermit-v2"
 
languageCode = "en-gb"

title = "maltby.dev"
enableGitInfo = true

pygmentsCodefences  = true
pygmentsUseClasses  = true

enableEmoji = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[params.author]
  name = "Maximus Maltby"

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  description = "maltby.dev"
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = "~/>&nbsp;"
  footerCopyright = '<a href="https://opensource.org/license/mit" target="_blank" rel="noopener">MIT</a>'
  bgImg = "https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHN0YXJyeSUyMHNreXxlbnwwfHwwfHx8MA%3D%3D"
  gitUrl = "https://github.com/maximusmaltby/maltby.dev"

  justifyContent = false

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = false
  readTime = true
  readTimeSeparator = ""
  # legacyLayout = false
  shareSocial = true
  # googleTagManager = "GTM-XXXXXXXX"
  # tagSymbol = "#"
  # categorySymbol = "⊲"
  # pinned = "Pinned Posts"
  # pinnedSVGname = "pin"
  # descriptionInPosts= true
  # initialPublish = "Initally Posted on: "
  # human = ["single","posts"]
  # noIndex = false
  # denyRobots = "noindex, nofollow, noarchive"
  # allowRobots = "index, follow"
  # siteNoIndex = false
  # noIndexPages = ["404 Page not found"]

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/maximusmaltby"
	
  [[params.socialLinks]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/maximusmaltby"

[menu]

  [[menu.main]]
    name = "portfolio"
    url = "https://portfolio.maltby.dev"
    weight = 9